{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valka.fullname" . }}-db
  labels:
    {{- include "valka.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.pgbouncer.enabled }}
  database-url: {{ printf "postgresql://%s:%s@localhost:5432/%s" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.database | quote }}
  {{- else }}
  database-url: {{ .Values.database.url | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.pgbouncer.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valka.fullname" . }}-pg
  labels:
    {{- include "valka.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
{{- end }}
