apiVersion: v1
kind: Service
metadata:
  name: {{ include "valka.fullname" . }}
  labels:
    {{- include "valka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "valka.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
